baseURL = 'https://example.org/'
languageCode = 'en-AU'
title = 'MapleMinis'
publishDir = "docs"

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Exploring the world of miniatures."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hello!'
homeIntroContent = """
I like to paint miniatures, sometimes I like to try my hand at creating them as well - I thought I'd share my journey here
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/user/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highlight on code blocks
#[markup]
##[markup.highlight]
style = 'algol'

# Giscus comments
#[params.giscus]
#enable = false
#repo = "user/repo"
#repoid = "repoId"
#category = "General"
#categoryid = "categoryId"
#mapping = "pathname"
#theme = "preferred_color_scheme"

[module]
[[module.imports]]
path = "github.com/tomfran/typo"
